# 1. NUMPY BASICS

In [2]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np


# Let's define a one-dimensional array 
my_list = [10,20,50,60,70]
my_list

[10, 20, 50, 60, 70]

In [3]:
# Let's create a numpy array from the list "my_list"

x = np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [4]:
type(x)

matrix = np.array([[4,6,8,7],[20,5,6,9]])
matrix


array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

In [5]:
# Multi-dimensional (Matrix definition) 

# Pass two sets of [] brackets inside the np.array() function separated by commas to determine each row of values
matrix = np.array([[4,6,8,7],[20,5,6,9]])


**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [7]:
matrix = np.array([[4,6,8,7],[20,5,6,9]])
matrix

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [8]:
# "rand()" uniform distribution between 0 and 1

x = np.random.rand(15)
x

array([0.20237169, 0.38697184, 0.05168162, 0.92132327, 0.36607364,
       0.66005604, 0.25220694, 0.82218709, 0.57859998, 0.89130908,
       0.51964282, 0.09316994, 0.33774538, 0.40757868, 0.85408699])

In [9]:
# you can create a matrix of random number as well
x = np.random.rand(5,5)
x

array([[9.59375349e-01, 3.94213784e-01, 6.09687384e-01, 9.74554604e-01,
        9.46492829e-01],
       [8.58836409e-01, 4.53581024e-01, 3.45538556e-01, 4.52933388e-01,
        6.98387391e-01],
       [9.96509225e-01, 5.94094960e-01, 4.23735587e-01, 2.77587987e-01,
        3.88740754e-01],
       [6.10899513e-02, 8.49350301e-04, 8.46523240e-01, 6.39482027e-01,
        8.27929230e-01],
       [1.13918508e-01, 4.00082345e-01, 8.16514270e-01, 5.16310260e-01,
        6.87019955e-01]])

In [10]:
# "randn()" normal distribution between 0 and 1
x = np.random.randn(10)
x


array([-1.35785235,  0.05179736,  1.36692285,  0.20259228,  1.25992598,
        1.53355608, -0.02760755, -1.58602922,  0.47881573,  0.26807661])

In [15]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(0,100)
x

70

In [16]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1,100,15)
x

array([47, 52,  5, 88, 45, 66, 18, 79, 35, 49, 75, 36, 22, 57, 37])

In [17]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
# Create an evenly spaced values with a step of 5
x = np.arange(1,50,5) # pass the range from and to, then the step
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [19]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(15)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [20]:
# Array of ones
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
# Matrices of ones
x = np.ones((15,15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [24]:
# Array of zeros
x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [35]:
# define a function that takes user input
def randarray():
    number = input('Please enter a positive integer') # save user input to number
    numArray = np.random.randint(0,number,20) # create randint array of 0 through to users input 20 times 
    print(numArray) # print

randarray()

[ 30 187 214  11   9  84  39 191  71  87 172 164 216  88 175 171 256  82
 141 149]


# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [6]:
# Let's define a one-dimensional array 
import numpy


my_list = [-30,4,50,60,29,15,22,90]
my_list

x = numpy.array(my_list) # convert a list into np arrays
x



array([-30,   4,  50,  60,  29,  15,  22,  90])

In [9]:
# Get Length of a numpy array
len(x)

8

In [10]:
# Get shape
x.shape

(8,)

In [11]:
# Obtain the datatype
x.dtype

dtype('int32')

In [12]:
# Reshape 1D array into a matrix
z = x.reshape(2,4)
z

# reshape will take the original values in the array and reshape it to the rows and # of values specified in reshape

array([[-30,   4,  50,  60],
       [ 29,  15,  22,  90]])

In [15]:
# Obtain the maximum element (value)
z.max()

90

In [16]:
# Obtain the minimum element (value)
z.min()

-30

In [17]:
# Obtain the location of the max element

x.argmax()

# this is useful to find index location for highest values in arrays

7

In [18]:
# Obtain the location of the min element
x.argmin()

0

**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array in which numbers range between 300 and 500 such that the difference between elements is 10**

In [89]:
my_array = np.arange(300,500,10)
my_array =  my_array.reshape(4,5)
my_array

array([[300, 310, 320, 330, 340],
       [350, 360, 370, 380, 390],
       [400, 410, 420, 430, 440],
       [450, 460, 470, 480, 490]])

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [94]:
my_array = np.random.randint(-1000,1000, size=(20,20))
my_array

print(my_array.max())
print(my_array.min())
print(my_array.mean())

print('The max of value array is {}, the min is {}, and the mean is {}'.format(my_array.max(),my_array.min(),my_array.mean()))

994
-998
26.3525
The max of value array is 994, the min is -998, and the mean is 26.3525


# 4. MATHEMATICAL OPERATIONS

In [95]:
# np.arange() returns an evenly spaced values within a given interval

x = numpy.arange(1,10)
x


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
y = numpy.arange(1,10)
y  

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
# Add 2 numpy arrays together
sum = x+y
sum

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [99]:
squared = x**2
squared

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [100]:
sqrt = numpy.sqrt(squared)
sqrt

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [101]:
z = numpy.exp(y)
z

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03])

**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

In [105]:
x_array = np.array([3,20,30])
y_array = np.array([4,6,7])

# to get the distance between two arrays square them, sum them, and get the square root 
dist = np.sqrt(x_array**2+y_array**2)
dist

array([ 5.        , 20.88061302, 30.8058436 ])

# 5. SLICING AND INDEXING 

In [106]:
x = numpy.array([20,40,50,21,15])
x

array([20, 40, 50, 21, 15])

In [113]:
# Access specific index from the numpy array

x[-1]
x[4]

15

In [114]:
# Starting from the first index 0 up until and NOT inlcluding the last element
x[0:3]

array([20, 40, 50])

In [115]:
# Broadcasting, altering several values in a numpy array at once
x[0:2] = 10
x

array([10, 10, 50, 21, 15])

In [118]:
# Let's define a two dimensional numpy array
matrix = numpy.random.randint(1,10,size=(5,5))
matrix



array([[3, 4, 2, 1, 2],
       [8, 8, 7, 9, 3],
       [6, 6, 7, 4, 1],
       [2, 7, 5, 6, 8],
       [8, 3, 4, 1, 3]])

In [120]:
# Get a row from a mtrix
matrix[0]

array([3, 4, 2, 1, 2])

In [126]:
# Get one element
matrix[0,2] # row index 0, column index 2 
matrix[3,3] # get the 6 out of the multi-dimensional matrix 
matrix[3][3]

6

In [127]:
minimatrix = matrix[:3] # obtain the first 3 rows of the matrix 
minimatrix

array([[3, 4, 2, 1, 2],
       [8, 8, 7, 9, 3],
       [6, 6, 7, 4, 1]])

In [143]:
minimatrix = matrix[1:3,1:3] # slice the 5x5 matrix to only pull the 4 numbers from row 2, col 2 to row 3 col 3 inclusive
minimatrix


array([[8, 7],
       [6, 7]])

**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



# 6. ELEMENTS SELECTION (CONDITIONAL)

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [ ]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300, 500, 10)
x.shape

In [ ]:
x = x.reshape(4, 5)
print(x)

**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

In [ ]:
X[:2, 3:]  = X[:2, 3:] * 2

In [ ]:
X

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X