# 1. NUMPY BASICS

In [2]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 
import numpy as np


# Let's define a one-dimensional array 
my_list = [10,20,50,60,70]
my_list

[10, 20, 50, 60, 70]

In [3]:
# Let's create a numpy array from the list "my_list"

x = np.array(my_list)
x

array([10, 20, 50, 60, 70])

In [4]:
type(x)

matrix = np.array([[4,6,8,7],[20,5,6,9]])
matrix


array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

In [5]:
# Multi-dimensional (Matrix definition) 

# Pass two sets of [] brackets inside the np.array() function separated by commas to determine each row of values
matrix = np.array([[4,6,8,7],[20,5,6,9]])


**MINI CHALLENGE #1:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [7]:
matrix = np.array([[4,6,8,7],[20,5,6,9]])
matrix

array([[ 4,  6,  8,  7],
       [20,  5,  6,  9]])

# 2. BUILT-IN METHODS AND FUNCTIONS 

In [8]:
# "rand()" uniform distribution between 0 and 1

x = np.random.rand(15)
x

array([0.20237169, 0.38697184, 0.05168162, 0.92132327, 0.36607364,
       0.66005604, 0.25220694, 0.82218709, 0.57859998, 0.89130908,
       0.51964282, 0.09316994, 0.33774538, 0.40757868, 0.85408699])

In [9]:
# you can create a matrix of random number as well
x = np.random.rand(5,5)
x

array([[9.59375349e-01, 3.94213784e-01, 6.09687384e-01, 9.74554604e-01,
        9.46492829e-01],
       [8.58836409e-01, 4.53581024e-01, 3.45538556e-01, 4.52933388e-01,
        6.98387391e-01],
       [9.96509225e-01, 5.94094960e-01, 4.23735587e-01, 2.77587987e-01,
        3.88740754e-01],
       [6.10899513e-02, 8.49350301e-04, 8.46523240e-01, 6.39482027e-01,
        8.27929230e-01],
       [1.13918508e-01, 4.00082345e-01, 8.16514270e-01, 5.16310260e-01,
        6.87019955e-01]])

In [10]:
# "randn()" normal distribution between 0 and 1
x = np.random.randn(10)
x


array([-1.35785235,  0.05179736,  1.36692285,  0.20259228,  1.25992598,
        1.53355608, -0.02760755, -1.58602922,  0.47881573,  0.26807661])

In [15]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(0,100)
x

70

In [16]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1,100,15)
x

array([47, 52,  5, 88, 45, 66, 18, 79, 35, 49, 75, 36, 22, 57, 37])

In [17]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1,50)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [18]:
# Create an evenly spaced values with a step of 5
x = np.arange(1,50,5) # pass the range from and to, then the step
x

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46])

In [19]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(15)
x

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [20]:
# Array of ones
x = np.ones(10)
x

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [23]:
# Matrices of ones
x = np.ones((15,15))
x

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.

In [24]:
# Array of zeros
x = np.zeros(50)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

**MINI CHALLENGE #2:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [35]:
# define a function that takes user input
def randarray():
    number = input('Please enter a positive integer') # save user input to number
    numArray = np.random.randint(0,number,20) # create randint array of 0 through to users input 20 times 
    print(numArray) # print

randarray()

[ 30 187 214  11   9  84  39 191  71  87 172 164 216  88 175 171 256  82
 141 149]


# 3. SHAPE, LENGTH, TYPE, RESHAPE, AND MAX/MIN VALUES

In [ ]:
# Let's define a one-dimensional array 


In [ ]:
# Get Length of a numpy array


In [ ]:
# Get shape


In [ ]:
# Obtain the datatype


In [ ]:
# Reshape 1D array into a matrix


In [ ]:
# Obtain the maximum element (value)


In [ ]:
# Obtain the minimum element (value)


In [ ]:
# Obtain the location of the max element


In [ ]:
# Obtain the location of the min element


**MINI CHALLENGE #3:**
- **Write a code that creates a 4x5 array inwhich numbers range between 300 and 500 such that the difference between elements is 10**

**MINI CHALLENGE #4:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

# 4. MATHEMATICAL OPERATIONS

In [ ]:
# np.arange() returns an evenly spaced values within a given interval


In [ ]:
# Add 2 numpy arrays together


**MINI CHALLENGE #5:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```

# 5. SLICING AND INDEXING 

In [ ]:
# Access specific index from the numpy array


In [ ]:
# Starting from the first index 0 up until and NOT inlcluding the last element


In [ ]:
# Broadcasting, altering several values in a numpy array at once


In [ ]:
# Let's define a two dimensional numpy array


In [ ]:
# Get a row from a mtrix


In [ ]:
# Get one element


**MINI CHALLENGE #6:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



# 6. ELEMENTS SELECTION (CONDITIONAL)

**MINI CHALLENGE #7:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


# EXCELLENT JOB!

# MINI CHALLENGES SOLUTIONS

**MINI CHALLENGE #1 SOLUTION:** 
- **Write a code that creates the following 2x4 numpy array**

```
[[4 6 8 7] 
[20 5 6 9]]
```

In [ ]:
x = np.array([[[4, 6, 8, 7] , [20, 5, 6, 9]]])
x

**MINI CHALLENGE #2 SOLUTION:**
- **Write a code that takes in a number x from the user and creates a 1x20 array with random numbers ranging from 0 to x**

In [ ]:
x = int(input("Please enter a positive integer value: "))
x = np.random.randint(1, x, 20)
x

**MINI CHALLENGE #3 SOLUTION:**
- **Write a code that creates a 4x5 array inwhich numbers ranging between 300 and 500 such that the difference between elements is 10**

In [ ]:
x = np.arange(300, 500, 10)
x.shape

In [ ]:
x = x.reshape(4, 5)
print(x)

**MINI CHALLENGE #4 SOLUTION:**
- **Write a code that creates a 20x20 numpy array of random values that ranges from -1000 to 1000 and obtain the maximum, minimum, and mean values** 

In [ ]:
x = np.random.randint(-1000, 1000, (20, 20))
print(x)
print('The maximum value is: {} and the minimum value is:{}'.format(x.min(), x.max()))

**MINI CHALLENGE #5 SOLUTION:**
- **Given the X and Y values below, obtain the distance between them**


```
X = [3, 20, 30]
Y = [4, 6, 7]
```




In [ ]:
X = np.array([3, 20, 30])
Y = np.array([4, 6, 7])
Z = np.sqrt(X**2 + Y**2)
Z

**MINI CHALLENGE #6 SOLUTION:**
- **In the following matrix, replace the last row with -1**
- **Multiply the 2x2 matrix in the upper right corner by 2**



```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```




In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])


In [ ]:
X[4] = 0
X

In [ ]:
X[:2, 3:]  = X[:2, 3:] * 2

In [ ]:
X

**MINI CHALLENGE #7 SOLUTION:**
- **In the following matrix, replace negative elements by 0 and replace odd elements with 25**


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [ ]:
X = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])

X[X%2==1] = 25
X[X<0] = 0
X